package com.marsinfotech.secforecast.services.core;

public enum ServiceState {
    UNITIALIZED, INITIALIZING, INITIALIZED, STARTING, STARTED, PRELOADING, PRELOADED, POSTSTARTING, POSTSTARTED,
    PAUSING, PAUSED, STOPPING, STOPPED, RESUMING, RESUMED, ERROR
}
